# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

# install minimal packages for debian slim images
RUN yum update && \
    yum install -y python3.6 sudo bash ca-certificates systemd systemd-sysv python3.6-pip python3.6 -dev && \
