---
name: Checkout
'on':
  push:
    branches:
      - dev
  schedule:
    - cron: "06 16 * * 1"
defaults:
  run:
    working-directory: 'rezizter.ansible_prom2teams'
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
