---
name: CI
#on: [push]
'on':
  push:
    branches:
      - dev
  schedule:
    - cron: "30 8 * * 0"
defaults:
  run:
    working-directory: 'rezizter.ansible_prom2teams'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'rezizter.ansible_prom2teams'
