 name: Github Action with a cronjob trigger
 on:
 schedule:
     - cron: "16 16 * * *"

 jobs:
 cronjob-based-github-action:
     name: Cronjob based github action
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     # - steps
     - uses: entepotenz/keep-github-actions-alive-min-dependencies@v1
